import os

configfile: "../config/config.yaml"

#micromamba_path = os.path.expandvars(config["micromamba_path"])
#micromamba_env = config["micromamba_env"]

conda_path = os.path.expandvars(config["conda_path"])
conda_env = config["conda_env"]

#shell.prefix(f"source {micromamba_path}; micromamba activate {micromamba_env}; ")
#shell.prefix("source $HOME/micromamba/etc/profile.d/micromamba.sh; micromamba activate varrna; ")
shell.prefix(f"source {conda_path}; conda activate {conda_env}; ")

include: "rules/setup.smk"

rule all:
    input:
        get_all_inputs()

include: "rules/process_bam.smk"
include: "rules/bam_to_fastq.smk"
include: "rules/salmon.smk"
include: "rules/variant_calling.smk"
include: "rules/filtering.smk"
include: "rules/annotations.smk"
include: "rules/query_vcfs.smk"
include: "rules/process_features.smk"
include: "rules/classify_variants.smk"
